repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: name-tests-test

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0.1
    hooks:
      - id: upgrade-type-hints

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml" ]
        additional_dependencies: [ "bandit[toml]" ]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        stages: [ push ]
        types: [ python ]
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true