default:
  model:
    cache_dir: "./models"
    embedding:
      dimension: 512
      image:
        name: "sentence-transformers/clip-ViT-B-32"
      text:
        name: "sentence-transformers/clip-ViT-B-32-multilingual-v1"
      metadata:
        name: "sentence-transformers/clip-ViT-B-32-multilingual-v1"
    captioning:
      name: "Salesforce/blip-image-captioning-large"
      max_length: 256
    detection:
      name: "jacoballessio/ai-image-detect-distilled"
      threshold: 0.95
    watermark:
      diffusion_model: "stabilityai/sdxl-turbo"
      encoder_name: "imatag/stable-signature-bzh-sdxl-vae-medium"
      decoder_name: "imatag/stable-signature-bzh-detector-resnet18"
      method: "rivaGan"

development:
  model:
    cache_dir: "/models"
  eva_backend:
    url: "http://localhost:8000"
    patch_endpoint: "/ai/image/update"
    backend_image_patch_route: "@format {this.eva_backend.url}{this.eva_backend.patch_endpoint}"
  
  bentoml:
    hf_offline: false
    api:
      workers: 1
      resources:
        cpu: 1
        memory: 2Gi
    embedding:
      workers: 1
      resources:
        cpu: 1
        memory: 4Gi
    inference:
      fast_batched_op_max_batch_size: 2
      fast_batched_op_max_latency_ms: 100
      slow_batched_op_max_batch_size: 2
      slow_batched_op_max_latency_ms: 100

  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    db: "eva_ai"
    url: "@format postgresql+asyncpg://{this.postgres.user}:{this.postgres.password}@{this.postgres.host}:{this.postgres.port}/{this.postgres.db}"

production:
  eva_backend:
    url: "https://api.production.example.com"
    patch_endpoint: "/ai/image/update"
    backend_image_patch_route: "@format {this.eva_backend.url}{this.eva_backend.patch_endpoint}"
  
  bentoml:
    hf_offline: true
    api:
      workers: 64
      resources:
        threads: 8
        memory: 16Gi
    embedding:
      workers: 8
      resources:
        threads: 8
        memory: 112Gi
    inference:
      fast_batched_op_max_batch_size: 64
      fast_batched_op_max_latency_ms: 100
      slow_batched_op_max_batch_size: 32
      slow_batched_op_max_latency_ms: 10000

  postgres:
    host: null
    port: null
    user: null
    password: null
    db: null
    url: "@format postgresql+asyncpg://{this.postgres.user}:{this.postgres.password}@{this.postgres.host}:{this.postgres.port}/{this.postgres.db}"

testing:
  eva_backend:
    url: "http://test-api:8000"
    patch_endpoint: "/ai/image/update"
    backend_image_patch_route: "@format {this.eva_backend.url}{this.eva_backend.patch_endpoint}"
  
  bentoml:
    hf_offline: false
    api:
      workers: 1
      resources:
        cpu: 1
        memory: 1Gi
    embedding:
      workers: 1
      resources:
        cpu: 1
        memory: 4Gi
    inference:
      fast_batched_op_max_batch_size: 2
      fast_batched_op_max_latency_ms: 100
      slow_batched_op_max_batch_size: 2
      slow_batched_op_max_latency_ms: 100

  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    db: "eva_ai_test"
    url: "@format postgresql+asyncpg://{this.postgres.user}:{this.postgres.password}@{this.postgres.host}:{this.postgres.port}/{this.postgres.db}"
