name: Container
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EVA_AI_MODEL__CACHE_DIR: ${{ github.event.inputs.EVA_AI_MODEL__CACHE_DIR || '/cache' }}  # This is a build time env. variable
      EVA_AI_MODEL__PRE_DOWNLOAD_DURING_BUILD: ${{ github.event.inputs.EVA_AI_MODEL__PRE_DOWNLOAD_DURING_BUILD || 'true' }}  # Will be baked into image if true
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Prepare python dependencies
        run: |
          pip install --upgrade --root-user-action=ignore -e .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: bentoml/containerize-push-action@v1
        with:
          context: ./
          bentofile: ./bentofile.yaml
          bento-tag: evagallery_ai_api:latest
          push: true
          tags: evagalleryone/ai:latest
