name: Container
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: bentoml/setup-bentoml-action@v1
        with:
          python-version: '3.12'
          bentoml-version: 'main'
          cache: 'pip'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Bento
        run: bentoml build

      - name: Build and push
        uses: bentoml/containerize-push-action@v1
        with:
          bento-tag: eva-gallery-ai:latest
          push: true
          tags: evagalleryone/ai:latest
