name: Push
on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  push:
    needs: build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        timeout-minutes: 3
        with:
          cache-from: type=gha

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        timeout-minutes: 3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        timeout-minutes: 10
        with:
          push: true
          tags: evagalleryone/ai:latest
          cache-from: type=gha